### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [ferociousdiablo/arduflower#1]
Hello!

I found link to this project from https://hackaday.com/2020/06/06/cheap-party-light-gets-arduino-upgrade/

Could you please add information about license of this repository — is it allowed to copy, change and use code in any purpose?
It would be great to see any popular open source license.

**Comment by ferociousdiablo** [comment]
Ah sorry I had forgotten about that!

Added GNU GPL v3 licence :)

**Comment by vazhnov** [comment]
Great! Thank you very much!
